### ISSUE TITLE
Manter o padrão de casing do texto original

### ISSUE THREAD

**Issue by vicentedealencar** [MiguelMedeiros/visao-libertaria#1]

**Comment by williamd1k0** [comment]
Acho que talvez seria melhor deixar isso em regex. Seria mais fácil de manter e customizar eventualmente.

**Comment by MiguelMedeiros** [comment]
hahaha Fiz tudo no Go Horse pra testar e subir no Google Extensions!
Mas bora arrumar isso ae galera! :D

**Comment by MiguelMedeiros** [comment]
Eu já arrumei fazendo com Regex mesmo! :)
