### ISSUE TITLE
Erro de escrita

### ISSUE THREAD

**Issue by br-arruda** [MiguelMedeiros/visao-libertaria#15]
https://github.com/MiguelMedeiros/visao-libertaria/blob/db810a01777052ac6515709ebce263b208d1186a/js/app.js#L219

deveria ser Organização, não Oranização.

**Comment by gustavo642** [comment]
Já arrumei no pull request, só falta o Miguel aceitar

**Comment by ghost** [comment]
Já corrigi, só falta ele aceitar o pull request.
