### ISSUE TITLE
Substituição de texto em formulários não deveria acontecer

### ISSUE THREAD

**Issue by br-arruda** [MiguelMedeiros/visao-libertaria#6]
Quase tive um problema no trabalho quando a extensão trocou termos de um texto que eu estava redigindo em um site kkkk

Para solucionar, 

1. daria para criar um whitelist na extensão e um botão "+" para adicionar o site atual lá. 

2. Outra solução para o que pensei é ignorar as tags com nome "form" e os seus elementos aninhados.

https://github.com/MiguelMedeiros/visao-libertaria/blob/403b66d86dcc95d302a4b0ec033edd68283ed34b/js/app.js#L98-L102

Alterando a linha 100-101 pra algo que ignore forms, tipo isso

```javascript
var element = elements[i];
if (element.nodeName.toLowerCase() == "form") {
    continue;
} 
```
Uma solução não exclui a outra e eu posso trabalhar nelas. O que acham?

**Comment by MiguelMedeiros** [comment]
Cara, show de bola a ideia! Me desculpe por arrumar, sem querer, uma confusão no seu trabalho! ahhaha :D
Pode fazer um PR com a alteração que eu subo sim! Valeu!

**Comment by vicentedealencar** [comment]
@brunoarruda vai fundo!
pensei uma coisa parecida e criei esse issue: https://github.com/MiguelMedeiros/visao-libertaria/issues/2
nao tive tempo pra pegar ele, mas acho que fecharia junto com esse. irado

**Comment by MiguelMedeiros** [comment]
Vou fechar esse Issue porque acabei de subir um [PR (#9)](https://github.com/MiguelMedeiros/visao-libertaria/pull/9) que faz exatamente isso! :)
